### ISSUE TITLE
Dependencies missing in requirements.txt

### ISSUE THREAD

**Issue by Cravtos** [osint-dev-team/osint-framework#44]
After execution of `pip3 install -r requirements.txt` and `python3 cli.py -h` it still misses some dependencies. 

* `Traceback (most recent call last):
  File "cli.py", line 12, in <module>
    from src.cli.interface.opener import show_opener
  File "/home/crav/Projects/osint-framework/src/cli/interface/opener.py", line 3, in <module>
    from art import text2art`
* `Traceback (most recent call last):
  File "cli.py", line 9, in <module>
    from src.cli.handlers.files import FileManager
  File "/home/crav/Projects/osint-framework/src/cli/handlers/files.py", line 8, in <module>
    from src.core.utils.log import Logger
  File "/home/crav/Projects/osint-framework/src/core/utils/log.py", line 9, in <module>
    from rich.logging import RichHandler
ModuleNotFoundError: No module named 'rich'
`

**Comment by manmolecular** [comment]
Thanks! That's my fault, you are totally right.
fixed: https://github.com/osint-dev-team/osint-framework/pull/46
